### ISSUE TITLE
updating to 7.5.0

### ISSUE THREAD

**Issue by renatasoares** [MinimalCompact/thumbor#136]
Hello! I am trying to update from 6.6.0 to 7.5.0 using aws config on loader/storage and result storage.

```
  #LOADER
  LOADER: "thumbor.compatibility.loader"
  COMPATIBILITY_LEGACY_LOADER: "tc_aws.loaders.s3_loader"
  TC_AWS_LOADER_BUCKET: "listing-forno-s3-quintoandar-com-br"
  TC_AWS_ENABLE_HTTP_LOADER: "False"
  TC_AWS_ALLOWED_BUCKETS: "False"

  #STORAGE
  STORAGE: thumbor.compatibility.storage
  COMPATIBILITY_LEGACY_STORAGE: tc_aws.storages.s3_storage
  TC_AWS_STORAGE_BUCKET: "5a-thumbor-test"
  TC_AWS_STORAGE_ROOT_PATH: "storage"
  TC_AWS_STORAGE_SSE: "False"
  TC_AWS_STORAGE_RRS: "False"

  #RESULT STORAGE
  RESULT_STORAGE: "thumbor.compatibility.result_storage"
  COMPATIBILITY_LEGACY_RESULT_STORAGE: "tc_aws.result_storages.s3_storage"
  RESULT_STORAGE_EXPIRATION_SECONDS: 0
  TC_AWS_RESULT_STORAGE_BUCKET: "5a-thumbor-test"
  TC_AWS_RESULT_STORAGE_ROOT_PATH: "result_storage"
  TC_AWS_MAX_RETRY: "0"
  TC_AWS_STORE_METADATA: "False"
```
  
  I am trying to run with these configurations but i keep getting the error bellow:
```
  
ERR tornado.access:ERROR 500 GET /unsafe/540x360/image.jpg
ERR thumbor:ERROR ERROR: Traceback (most recent call last):
ERR   File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1786, in _execute
ERR     result = await result
ERR   File "/usr/local/lib/python3.9/site-packages/thumbor/handlers/imaging.py", line 119, in get
ERR     return await self.check_image(kw)
ERR   File "/usr/local/lib/python3.9/site-packages/thumbor/handlers/imaging.py", line 28, in check_image
ERR     exists = await self.context.modules.storage.exists(
ERR   File "/usr/local/lib/python3.9/site-packages/thumbor/compatibility/storage.py", line 48, in exists
ERR     path, func=self.storage.exists, *args, **kw
ERR   File "/usr/local/lib/python3.9/site-packages/thumbor/compatibility/storage.py", line 20, in storage
ERR     raise RuntimeError(
ERR RuntimeError: The 'COMPATIBILITY_LEGACY_STORAGE' configuration should point to a valid storage when using compatibility storage.
```

Could someone help me to understand why is not working? thanks!

**Comment by gingerlime** [comment]
Perhaps this is something to ask the [Thumbor project](https://github.com/thumbor/thumbor)?
