### ISSUE TITLE
HTTP request sent, awaiting response... 504 Gateway Timeout

### ISSUE THREAD

**Issue by pnlinh** [MinimalCompact/thumbor#144]
Hi,

I have issue when using thumbor docker container, could you please take a look

### Step to reproduce
- Init thumbor container
```
docker run --rm --name=thumbor --security-opt seccomp:unconfined -e THUMBOR_NUM_PROCESSES=1 ghcr.io/minimalcompact/thumbor
```

- Verify image
```
curl -I 192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 20 Oct 2023 15:31:00 GMT
Content-Type: image/jpeg
Content-Length: 134900
Last-Modified: Wed, 14 Sep 2022 07:53:28 GMT
Connection: keep-alive
ETag: "63218878-20ef4"
Expires: Sat, 19 Oct 2024 15:31:00 GMT
Cache-Control: max-age=31536000
Accept-Ranges: bytes

```
- Get thumbor IP
```
docker inspect thumbor | grep -i IPAddress

            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",
```
- Test resize image with thumbor
```
wget http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg

--2023-10-20 22:32:29--  http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
Connecting to 172.17.0.2:80... connected.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2023-10-20 22:32:35--  (try: 2)  http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
Reusing existing connection to 172.17.0.2:80.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2023-10-20 22:32:42--  (try: 3)  http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
Reusing existing connection to 172.17.0.2:80.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2023-10-20 22:32:50--  (try: 4)  http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
Reusing existing connection to 172.17.0.2:80.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2023-10-20 22:32:59--  (try: 5)  http://172.17.0.2/unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg
Reusing existing connection to 172.17.0.2:80.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.


```

- Thumbor container log
```
2023-10-20 15:33:25 thumbor:WARNING ERROR retrieving image http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg: HTTP 599: Timeout while connecting
2023-10-20 15:33:25 tornado.access:ERROR 504 GET /unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg (172.17.0.1) 5003.96ms
2023-10-20 15:33:37 thumbor:WARNING ERROR retrieving image http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg: HTTP 599: Timeout while connecting
2023-10-20 15:33:37 tornado.access:ERROR 504 GET /unsafe/500x150/http://192.168.0.2/images/2022/09/14/769-1663142008-7525.jpg (172.17.0.1) 5005.73ms
```

**Comment by gingerlime** [comment]
Hi @pnlinh. It looks like a networking issue. 192.168.0.x is on a network that isn't reachable by your docker container most likely.

**Comment by pnlinh** [comment]
> Hi @pnlinh. It looks like a networking issue. 192.168.0.x is on a network that isn't reachable by your docker container most likely.
> 
> You can test it using the example from the readme:
> 
> ```
> $ docker run -p 80:80 ghcr.io/minimalcompact/thumbor
> $ wget http://localhost/unsafe/500x150/iili.io/H8m6pHv.png
> ```

@gingerlime, i have this issue when follow example from the readme

```
docker run -p 81:80 ghcr.io/minimalcompact/thumbor
---> Starting thumbor with 1 processes...
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 3: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 3: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 158, in main
    importer = get_importer(config)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 63, in get_importer
    importer.import_modules()
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 81, in import_modules
    self.import_item("ENGINE", "Engine")
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 144, in import_item
    module = self.import_class(f"{conf_value}.{class_name}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 56, in import_class
    kls = import_class(name, get_module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 20, in import_class
    module = import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/thumbor/engines/pil.py", line 22, in <module>
    from thumbor.engines.extensions.pil import GifWriter
  File "/usr/local/lib/python3.11/site-packages/thumbor/engines/extensions/pil.py", line 80, in <module>
    import numpy as np
  File "/usr/local/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 216, in _lock_unlock_module
KeyboardInterrupt
```

**Comment by gingerlime** [comment]
I cannot reproduce it. Please check your system / docker. Perhaps it's a permission issue, so you can try running it on a higher port, or use `--privileged` ?

**Comment by pnlinh** [comment]
@gingerlime it works for me, thank for your support

**Comment by pnlinh** [comment]
I'm using Nginx proxy manager and Thumbor on one server, so that solution is:

- Find my source IP Address
```
docker inspect <container_name> | grep -i IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.19.0.4",
```
- Edit `/etc/hosts` and add docker container IP for public domain
```
172.19.0.4 domain.com
```
-  Testing Thumbor
```

```

**Comment by gingerlime** [comment]
Good to hear you got it worked out @pnlinh. You might want to take a look at the companion [Nginx proxy cache](https://github.com/MinimalCompact/thumbor/blob/master/nginx-proxy-cache/README.md) and using `docker-compose` to connect things together. There are some [recipes](https://github.com/MinimalCompact/thumbor/tree/master/recipes/docker-compose) available for docker-compose to get you started.

The nginx proxy cache can hugely improve performance of your thumbor and reduce load. It's entirely optional of course.

**Comment by pnlinh** [comment]
@gingerlime Nice, thanks for your advice.
