### ISSUE TITLE
Cannot import name 'Sentinel' from 'redis' (/usr/local/lib/python3.11/site-packages/redis/__init__.py)

### ISSUE THREAD

**Issue by silviu-social1st-ro** [MinimalCompact/thumbor#149]
Hello,

I tried your docker image on 7.7.1 and 7.6.0 versions and i get an error about module Sentinel from Redis whenever I try to enable queued detector. With standard detectors, like thumbor.detectors.feature_detector, it starts up ok.
Error is:
```
---> Starting thumbor with 8 processes...
Traceback (most recent call last):
  File "/usr/local/bin/thumbor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 158, in main
    importer = get_importer(config)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 63, in get_importer
    importer.import_modules()
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 86, in import_modules
    self.import_item("DETECTORS", "Detector", is_multiple=True)
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 135, in import_item
    self.load_multiple_item(
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 167, in load_multiple_item
    module = self.import_class(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 56, in import_class
    kls = import_class(name, get_module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/importer.py", line 20, in import_class
    module = import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/thumbor/detectors/queued_detector/__init__.py", line 12, in <module>
    from redis import Redis, RedisError, Sentinel
ImportError: cannot import name 'Sentinel' from 'redis' (/usr/local/lib/python3.11/site-packages/redis/__init__.py)
```

This is my redis setup:
      - REDIS_QUEUE_MODE = "single_node" //also without option set
      - REDIS_QUEUE_SERVER_HOST=redis
      - REDIS_QUEUE_SERVER_PORT=6379
      - REDIS_QUEUE_SERVER_DB=0
     

I installed inside the docker image redis-cli and ping, I can reach and connect to redis host from within the thumbor docker instance, it's not a connectivity issue.

**Comment by gingerlime** [comment]
Perhaps something to report upstream to the thumbor project?

**Comment by silviu-social1st-ro** [comment]
> Perhaps something to report upstream to the thumbor project?

No, ithe issue is in the Dockerfile. I changed the required redis version in the requirements.txt file and it works. [ redis==5.0.1 ]
I think this project is using an old python redis version for thumbor ....

Thanks!
