### ISSUE TITLE
smart crop causes internal server error 500 response

### ISSUE THREAD

**Issue by hari56** [MinimalCompact/thumbor#163]
If you call  http://localhost:port/unsafe/meta/10x10/smart/https%3A%2F%2Fgithub.com%2Fthumbor%2Fthumbor%2Fraw%2Fmaster%2Fexample.jpg you get an internal server error. This is the stack trace of the docker container. Is there a way to fix that or is there any other solution? Thanks in advance

```
2024-09-03 12:11:01 thumbor:DEBUG METRICS: inc: response.count:1
2024-09-03 12:11:01 thumbor:DEBUG METRICS: inc: response.smart.count:1
2024-09-03 12:11:01 thumbor:DEBUG METRICS: timing: response.smart.latency:1
2024-09-03 12:11:01 thumbor:DEBUG METRICS: inc: storage.miss:1
2024-09-03 12:11:02 thumbor:DEBUG METRICS: timing: original_image.fetch.200.github_com:813
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: original_image.fetch.200.github_com:1
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: original_image.status.200:1
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: original_image.status.200.github_com:1
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: original_image.response_bytes:217688

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/bin/thumbor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/thumbor/server.py", line 164, in main
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 116, in check_image
    return await self.execute_image_operations()
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 205, in execute_image_operations
    await self.get_image()
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 305, in get_image
    await self.context.transformer.transform()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 37, in transform
    await self.smart_detect()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 166, in smart_detect
    await self.do_smart_detection()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 189, in do_smart_detection
    focal_points = await detectors[0](
  File "/usr/local/lib/python3.11/site-packages/thumbor/detectors/face_detector/__init__.py", line 21, in __init__
    self.load_cascade_file(
  File "/usr/local/lib/python3.11/site-packages/thumbor/detectors/local_detector.py", line 22, in load_cascade_file
    import cv2  # noqa pylint: disable=import-error,import-outside-toplevel
AttributeError: _ARRAY_API not found
2024-09-03 12:11:02 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/imaging.py", line 116, in check_image
    return await self.execute_image_operations()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 205, in execute_image_operations
    await self.get_image()
  File "/usr/local/lib/python3.11/site-packages/thumbor/handlers/__init__.py", line 305, in get_image
    await self.context.transformer.transform()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 37, in transform
    await self.smart_detect()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 166, in smart_detect
    await self.do_smart_detection()
  File "/usr/local/lib/python3.11/site-packages/thumbor/transformer.py", line 189, in do_smart_detection
    focal_points = await detectors[0](
                         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/thumbor/detectors/face_detector/__init__.py", line 21, in __init__
    self.load_cascade_file(
  File "/usr/local/lib/python3.11/site-packages/thumbor/detectors/local_detector.py", line 22, in load_cascade_file
    import cv2  # noqa pylint: disable=import-error,import-outside-toplevel
    ^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import

2024-09-03 12:11:02 tornado.access:ERROR 500 GET /unsafe/meta/10x10/smart/https%3A%2F%2Fgithub.com%2Fthumbor%2Fthumbor%2Fraw%2Fmaster%2Fexample.jpg (172.17.0.1) 820.87ms
2024-09-03 12:11:02 thumbor:DEBUG METRICS: timing: response.time:819
2024-09-03 12:11:02 thumbor:DEBUG METRICS: timing: response.time.500:819
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: response.status.500:1
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: response.count:1
2024-09-03 12:11:02 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico
2024-09-03 12:11:02 tornado.access:WARNING 400 GET /favicon.ico (172.17.0.1) 1.85ms
2024-09-03 12:11:02 thumbor:DEBUG METRICS: timing: response.time:0
2024-09-03 12:11:02 thumbor:DEBUG METRICS: timing: response.time.400:0
2024-09-03 12:11:02 thumbor:DEBUG METRICS: inc: response.status.400:1


```

**Comment by gingerlime** [comment]
Would you be able to test with the latest version? if you can still reproduce using docker-compose.yml, please re-open with clear reproduction steps.
